title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# Activaremos la búsqueda en la página.
# Soporta True (defaut) y False
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 5
  rel_url: true
  button: false
nav_external_links_new_tab: true
nav_enabled: true
heading_anchors: true
last_edit_timestamp: true

color_scheme: dark
  
url: https://Helox-t0.github.io

